name: Bump-n-Release

# NOTE: The change log is only updated in the remote upon release (in `bump-release` job)

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      package:
        description: The package to release
        type: choice
        required: true
        default: cpp-linter
        options:
          - cpp-linter
          - cpp-linter-js
          - cpp-linter-py
          - clang-tools-manager
      component:
        description: The version component to increase
        type: choice
        required: true
        default: patch
        options:
          - major
          - minor
          - patch
          - rc

run-name: >-
  ${{ inputs.package && 'Deploy ' || 'Show Unreleased Changes' }}
  ${{ inputs.package || '' }}

permissions: {}

jobs:
  bump-release:
    if: github.event_name == 'workflow_dispatch'
    name: Bump ${{ inputs.component }} version of ${{ inputs.package }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1
        with:
          token: ${{ secrets.BUMP_N_RELEASE }}
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: true # needed for `git push`
      - name: Set up Python
        if: inputs.package == 'cpp-linter-py'
        uses: actions/setup-python@v7.0.0
        with:
          python-version: 3.x
      - name: Install Node.js
        if: inputs.package == 'cpp-linter-js'
        uses: actions/setup-node@v7
        with:
          node-version: 24.x
      - run: yarn install
        if: inputs.package == 'cpp-linter-js'
      - uses: cargo-bins/cargo-binstall@b874e25ea559687bec77e281e9b271aa1367b624 # v1.23.0
      - run: cargo binstall -y git-cliff
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Install cargo-edit
        run: >-
          cargo install cargo-edit
          --locked
          --no-default-features
          --features set-version
      - name: Install nushell
        uses: hustcer/setup-nu@9215c80adb545a85c419d5085b76eb6d082f49e7 # v3.27
      - name: Bump ${{ inputs.component }} version
        env:
          GITHUB_TOKEN: ${{ secrets.BUMP_N_RELEASE }}
          GH_TOKEN: ${{ secrets.BUMP_N_RELEASE }}
        run: nu .github/workflows/bump-n-release.nu ${{ inputs.package }} ${{ inputs.component }}
        id: tagged

  get-changed-pkgs:
    if: github.event_name != 'workflow_dispatch' && !startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    outputs:
      pkgs: ${{ steps.get-pkgs.outputs.pkgs }}
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install nushell
        uses: hustcer/setup-nu@9215c80adb545a85c419d5085b76eb6d082f49e7 # v3.27
      - name: Get changed packages
        id: get-pkgs
        shell: nu {0}
        run: |-
          print (pwd)
          use ("./.github/workflows/bump-n-release.nu" | path expand) get-changed-pkgs
          let pkgs = (get-changed-pkgs)
          $"pkgs=($pkgs)\n" | save --append $env.GITHUB_OUTPUT

  update-changelog:
    if: github.event_name != 'workflow_dispatch'
    needs: [get-changed-pkgs]
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pkg: ${{ fromJSON(needs.get-changed-pkgs.outputs.pkgs) }}
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: false
      - uses: cargo-bins/cargo-binstall@b874e25ea559687bec77e281e9b271aa1367b624 # v1.23.0
      - run: cargo binstall -y git-cliff
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Install nushell
        uses: hustcer/setup-nu@9215c80adb545a85c419d5085b76eb6d082f49e7 # v3.27
      - name: Generate a release notes
        env:
          PKG: ${{ matrix.pkg }}
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_REPO: ${{ github.repository }}
          GIT_CLIFF_CONFIG: .config/cliff.toml
        shell: nu {0}
        run: |-
          use ("./.github/workflows/bump-n-release.nu" | path expand) gen-changes
          gen-changes $env.PKG --unreleased
          let out = open --raw .config/ReleaseNotes.md
          $"## ($env.PKG)\n\n($out)" | save --append $env.GITHUB_STEP_SUMMARY
