name: Node.js builds

on:
  push:
    branches: [main]
    paths:
      - cpp-linter/src/**
      - cpp-linter/Cargo.toml
      - Cargo.toml
      - Cargo.lock
      - bindings/node/**
      - package.json
      - yarn.lock
      - .github/workflows/node-js-packaging.yml
    tags:
      - 'cpp-linter-js/v*'
  pull_request:
    branches: [main]
    paths:
      - cpp-linter/src/**
      - cpp-linter/Cargo.toml
      - Cargo.toml
      - Cargo.lock
      - bindings/node/**
      - package.json
      - yarn.lock
      - .github/workflows/node-js-packaging.yml

env:
  DEBUG: napi:*
  APP_NAME: cpp-linter
  MACOSX_DEPLOYMENT_TARGET: '10.13'

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  seed-build-script:
    name: Pre-seed static binaries' versions
    uses: $/.github/workflows/pre-seed-versions.yml

  build:
    needs: [seed-build-script]
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-latest
            target: x86_64-apple-darwin
            build: yarn build --target x86_64-apple-darwin
          - host: windows-latest
            build: yarn build --target x86_64-pc-windows-msvc
            target: x86_64-pc-windows-msvc
          - host: windows-latest
            build: yarn build --target i686-pc-windows-msvc
            target: i686-pc-windows-msvc
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            build: yarn build --target x86_64-unknown-linux-gnu --use-cross
          - host: ubuntu-latest
            target: x86_64-unknown-linux-musl
            build: yarn build --target x86_64-unknown-linux-musl -x
          - host: macos-latest
            target: aarch64-apple-darwin
            build: yarn build --target aarch64-apple-darwin
          - host: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            build: yarn build --target aarch64-unknown-linux-gnu --use-cross
          - host: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            build: yarn build --target armv7-unknown-linux-gnueabihf --use-cross
          - host: ubuntu-latest
            target: aarch64-unknown-linux-musl
            build: yarn build --target aarch64-unknown-linux-musl -x
          - host: windows-latest
            target: aarch64-pc-windows-msvc
            build: yarn build --target aarch64-pc-windows-msvc
    name: Build ${{ matrix.settings.target }}
    runs-on: ${{ matrix.settings.host }}
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - name: Setup node
        uses: actions/setup-node@v7
        with:
          node-version: 22
          cache: yarn # zizmor: ignore[cache-poisoning]
      - name: Setup Rust
        run: |-
          rustup update stable --no-self-update
          rustup target add ${{ matrix.settings.target }}
      - name: Cache cargo
        uses: actions/cache@v6.1.0 # zizmor: ignore[cache-poisoning]
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.napi-rs
            .cargo-cache
            target/
          key: ${{ matrix.settings.target }}-cargo-${{ matrix.settings.host }}
      - uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29 # v2.2.1
        if: ${{ endsWith(matrix.settings.build, ' -x') }}
        with:
          version: 0.14.1
          use-cache: true # zizmor: ignore[cache-poisoning]
      - name: Install cargo-binstall
        if: endsWith(matrix.settings.build, ' -x') || endsWith(matrix.settings.build, '--use-cross')
        uses: cargo-bins/cargo-binstall@b874e25ea559687bec77e281e9b271aa1367b624 # v1.23.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Install ${{endsWith(matrix.settings.build, ' -x') && 'cargo-zigbuild' || 'cargo-cross'}}
        if: endsWith(matrix.settings.build, ' -x') || endsWith(matrix.settings.build, '--use-cross')
        env:
          GITHUB_TOKEN: ${{ github.token }}
          tool: ${{endsWith(matrix.settings.build, ' -x') && 'cargo-zigbuild' || 'cross'}}
        run: cargo binstall -y $tool
      - name: Setup toolchain
        run: ${{ matrix.settings.setup }}
        if: ${{ matrix.settings.setup }}
        shell: bash
      - name: Install dependencies
        run: yarn install
      - name: Restore build script seed
        uses: actions/download-artifact@v8
        with:
          name: ${{ needs.seed-build-script.outputs.artifact-name }}
          path: clang-tools-manager
      - name: Build
        run: ${{ matrix.settings.build }}
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: bindings-${{ matrix.settings.target }}
          path: |
            bindings/node/${{ env.APP_NAME }}.*.node
            bindings/node/${{ env.APP_NAME }}.*.wasm
          if-no-files-found: error
  build-freebsd:
    needs: [seed-build-script]
    runs-on: ubuntu-latest
    name: Build FreeBSD
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - name: setup FreeBSD VM
        uses: cross-platform-actions/action@faa0c6197e94aacf1c5956460152c8380d3560a5 # v1.5.0
        env:
          DEBUG: napi:*
          RUSTUP_IO_THREADS: 1
        with:
          operating_system: freebsd
          version: '15.0'
          memory: 8G
          cpu_count: 3
          environment_variables: DEBUG RUSTUP_IO_THREADS
      - name: Restore build script seed
        uses: actions/download-artifact@v8
        with:
          name: ${{ needs.seed-build-script.outputs.artifact-name }}
          path: clang-tools-manager
      - name: Build
        shell: cpa.sh {0}
        run: |-
          sudo pkg install -y -f curl node libnghttp2 npm cmake
          sudo npm install -g yarn --ignore-scripts
          curl https://sh.rustup.rs -sSf --output rustup.sh
          sh rustup.sh -y --profile minimal --default-toolchain stable
          . "$HOME/.cargo/env"
          echo "~~~~ rustc --version ~~~~"
          rustc --version
          echo "~~~~ node -v ~~~~"
          node -v
          echo "~~~~ yarn --version ~~~~"
          yarn --version
          pwd
          ls -lah
          whoami
          env
          freebsd-version
          yarn install
          yarn build
          rm -rf node_modules
          rm -rf target
          rm -rf .yarn/cache
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: bindings-freebsd
          path: bindings/node/${{ env.APP_NAME }}.*.node
          if-no-files-found: error
  test-macOS-windows-binding:
    name: Test ${{ matrix.settings.target }} - node@${{ matrix.node }}
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: windows-latest
            target: x86_64-pc-windows-msvc
            architecture: x64
          - host: windows-11-arm
            target: aarch64-pc-windows-msvc
            architecture: arm64
          - host: macos-latest
            target: aarch64-apple-darwin
            architecture: arm64
          - host: macos-latest
            target: x86_64-apple-darwin
            architecture: x64
        node:
          - '22'
          - '24'
    runs-on: ${{ matrix.settings.host }}
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - name: Setup node
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node }}
          cache: yarn # zizmor: ignore[cache-poisoning]
          architecture: ${{ matrix.settings.architecture }}
      - name: Install dependencies
        run: yarn install
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: bindings-${{ matrix.settings.target }}
          path: bindings/node
      - name: List packages
        run: ls -R .
        shell: bash
      - name: Test bindings
        run: yarn test
  test-linux-binding:
    name: Test ${{ matrix.target }} - node@${{ matrix.node }}
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
          - armv7-unknown-linux-gnueabihf
        node:
          - '22'
          - '24'
        exclude:
          - target: armv7-unknown-linux-gnueabihf
            node: '24' # no docker image node:24-slim for armv7
    runs-on: ${{ contains(matrix.target, 'aarch64') && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - name: Setup node
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node }}
          cache: yarn # zizmor: ignore[cache-poisoning]
      - name: Output docker params
        id: docker
        run: |
          node -e "
            if ('${{ matrix.target }}'.startsWith('aarch64')) {
              console.log('PLATFORM=linux/arm64')
            } else if ('${{ matrix.target }}'.startsWith('armv7')) {
              console.log('PLATFORM=linux/arm/v7')
            } else {
              console.log('PLATFORM=linux/amd64')
            }
          " >> $GITHUB_OUTPUT
          node -e "
            if ('${{ matrix.target }}'.endsWith('-musl')) {
              console.log('IMAGE=node:${{ matrix.node }}-alpine')
            } else {
              console.log('IMAGE=node:${{ matrix.node }}-slim')
            }
          " >> $GITHUB_OUTPUT
      - name: Install dependencies
        run: |
          yarn config set --json supportedArchitectures.cpu '["current", "arm64", "x64", "arm"]'
          yarn config set --json supportedArchitectures.libc '["current", "musl", "gnu"]'
          yarn install
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: bindings-${{ matrix.target }}
          path: bindings/node
      - name: List packages
        run: ls -R .
        shell: bash
      - name: Set up QEMU
        uses: docker/setup-qemu-action@1f40c72289eff860ee54a304f1438e3cff362e0a # v4.3.0
        if: ${{ contains(matrix.target, 'armv7') }}
        with:
          platforms: all
      - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        if: ${{ contains(matrix.target, 'armv7') }}
      - name: Test bindings
        if: matrix.target != 'x86_64-unknown-linux-gnu'
        uses: tj-actions/docker-run@1d25a677da8f1243a138dc5db21e307e92986ffe # v2.2.1
        with:
          image: ${{ steps.docker.outputs.IMAGE }}
          name: test-${{ matrix.target }}
          options: >- # zizmor: ignore[template-injection]
            -v ${{ github.workspace }}:${{ github.workspace }}
            -w ${{ github.workspace }}
            --platform ${{ steps.docker.outputs.PLATFORM }}
          args: yarn test
      - name: Test x86_64-unknown-linux-gnu
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: yarn test
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      # needed for trusted publishing
      id-token: write
    needs:
      - build-freebsd
      - test-macOS-windows-binding
      - test-linux-binding
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - name: Setup node
        uses: actions/setup-node@v7
        with:
          node-version: 24
          package-manager-cache: false
      - name: Install dependencies
        run: yarn install
      - name: Create npm dirs
        working-directory: bindings/node
        run: yarn napi create-npm-dirs
      - name: Download all artifacts
        uses: actions/download-artifact@v8
        with:
          path: bindings/node/artifacts
      - name: Move artifacts
        run: yarn artifacts
      - name: List packages
        run: ls -R ./npm
        working-directory: bindings/node
        shell: bash
      - name: Publish
        if: startsWith(github.ref, 'refs/tags/cpp-linter-js/v')
        working-directory: bindings/node
        run: npm publish ${{ contains(github.ref_name, '-rc') && '--tag next' || '' }}
