name: "Test CI"

on:
  push:
    branches: [main]
    paths:
      - cpp-linter/**
      - clang-tools-manager/**
      - Cargo.toml
      - Cargo.lock
      - .github/workflows/run-dev-tests.yml
  pull_request:
    branches: [main]
    paths:
      - cpp-linter/**
      - clang-tools-manager/**
      - Cargo.toml
      - Cargo.lock
      - .github/workflows/run-dev-tests.yml

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  seed-build-script:
    name: Pre-seed static binaries' versions
    uses: $/.github/workflows/pre-seed-versions.yml

  test:
    needs: [seed-build-script]
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest", ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false

      - name: Setup Rust
        run: |-
          rustup update --no-self-update
          rustup component add llvm-tools-preview

      # https://docs.rs/openssl/latest/openssl/#automatic
      # - name: Install OpenSSL (Linux)
      #   if: runner.os == 'Linux'
      #   run: sudo apt-get install -y pkg-config libssl-dev
      # - name: Install OpenSSL (MacOS)
      #   if: runner.os == 'macOS'
      #   run: brew install openssl@3
      # - name: Install OpenSSL (Windows)
      #   if: runner.os == 'Windows'
      #   run: vcpkg install openssl

      - uses: cargo-bins/cargo-binstall@b874e25ea559687bec77e281e9b271aa1367b624 # v1.23.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Install third-party binaries
        run: >-
          cargo binstall -y --locked cargo-nextest cargo-llvm-cov nur nu
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - uses: actions/setup-python@v7.0.0
        with:
          python-version: 3.x

      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      # # https://github.com/ninja-build/ninja/wiki/Pre-built-Ninja-packages
      - name: Install ninja (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get install ninja-build
      - name: Install ninja (Windows)
        if: runner.os == 'Windows'
        run: choco install ninja

      - name: Cache .cargo locked resources
        uses: actions/cache@v6.1.0
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-tests-cargo-${{ hashFiles('Cargo.lock') }}
      - name: Fetch .cargo locked resources
        run: cargo fetch

      - if: runner.os == 'Linux'
        run: sudo apt-get update

      - name: Install nushell
        uses: hustcer/setup-nu@9215c80adb545a85c419d5085b76eb6d082f49e7 # v3.27

      - name: Restore build script seed
        uses: actions/download-artifact@v8
        with:
          name: ${{ needs.seed-build-script.outputs.artifact-name }}
          path: clang-tools-manager

      - name: Run test suite
        shell: nu {0}
        run: |-
          let version_info = open "clang-tools-manager/versions.json"
          mut max_ver = 0
          mut min_ver = 99
          for ver in ($version_info.llvm_versions | columns) {
            let ver = $ver | into int
            if ($ver < $min_ver) {
              $min_ver = $ver
            }
            if ($ver > $max_ver) {
              $max_ver = $ver
            }
          }
          let min_ver = $min_ver # make immutable
          for $ver in ($min_ver..$max_ver) {
            print $"::group::Testing with clang v($ver)"
            with-env { CLANG_VERSION: $"($ver)" } {
              nur test --profile warmup
              let test_profile = (
                if ($ver == $min_ver) { "all" } else { "ci" }
              )
              nur test --profile $test_profile
            }
            print "::endgroup::"
          }

      - name: Generate Coverage HTML report
        run: nur test html

      - name: Upload coverage data
        uses: actions/upload-artifact@v7
        with:
          name: HTML_report-${{ runner.os }}
          path: target/llvm-cov/html

      - name: Generate Coverage lcov report
        run: nur test lcov

      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: lcov.info
          fail_ci_if_error: true # optional (default = false)
